
name: pypv
channels:
    - BACREDITFLOW-conda/main
    - conda-shared
    - conda-forge
dependencies:
    # Core dependencies of pypv
    - python ==3.7.10
    - dask ==2.20.0
    - numba ==0.50.1
    - numpy ==1.18.5
    - openpyxl ==3.0.7
    - pandas ==1.0.5
    - pyyaml ==5.3.1
    - requests ==2.23.0
    - s3fs ==0.4.2  # needed for some of the unit tests here and in the federated models that interact with S3
    - xlrd ==1.2.0  # Not directly imported but required to work with .xls files

    # For use when integration testing
    - pylava >=2021.02.24  # even when working with federated models, PyLava should cause no conflicts
    - creditflow >=0.21.9
    - jupyter ==1.0.0  # ipython will be installed as well

    # For developing MD utils
    - awscli ==1.18.76
    - boto3 ==1.13.26
    - botocore ==1.16.26
    - hubble ==0.7.3

    # For testing
    - flake8 ==3.8.4
    - pytest ==5.4.3
    - pytest-cov ==2.10.1
    - pytest-xdist ==1.33.0
    - moto ==1.3.16